# Generated by Django 2.0.13 on 2020-08-12 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200812_1226'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='users',
        #     name='id',
        #     field=models.AutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
        #     preserve_default=False,
        # ),
        # migrations.AlterField(
        #     model_name='users',
        #     name='user_id',
        #     field=models.CharField(max_length=128, unique=True),
        # ),
    ]
