# Generated by Django 2.0.13 on 2020-08-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schedule_user'),
        ('ticket', '0008_remove_ticket_user'),
        ('accounts', '0007_auto_20200813_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
