# Generated by Django 2.0.13 on 2020-08-09 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20200810_0629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_data', models.DateTimeField()),
                ('schedule_desc', models.CharField(max_length=256)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.Users')),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
