# Generated by Django 2.0.13 on 2020-12-04 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_name', models.CharField(blank=True, max_length=128)),
                ('schedule_date', models.DateTimeField()),
                ('schedule_desc', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'schedule',
            },
        ),
    ]
