# Generated by Django 2.0.13 on 2020-08-10 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200810_0629'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='user_id',
        ),
        migrations.AddField(
            model_name='schedule',
            name='schedule_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='schedule',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='accounts.Users'),
            preserve_default=False,
        ),
    ]
