# Generated by Django 2.0.13 on 2020-08-10 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20200810_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_data',
            new_name='schedule_date',
        ),
    ]
