# Generated by Django 2.0.13 on 2020-08-15 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=200)),
                ('user_num', models.IntegerField()),
                ('use_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.Lesson_info')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
