# Generated by Django 2.0.13 on 2020-08-15 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lesson_info',
            table='lesson_info',
        ),
        migrations.AlterModelTable(
            name='lesson_user',
            table='lesson_user',
        ),
    ]
