# Generated by Django 2.0.13 on 2020-12-04 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='TicketLog',
        ),
    ]
