# Generated by Django 2.0.13 on 2020-08-11 01:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20200810_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='expired_date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_use',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='started_date',
            field=models.DateTimeField(default=None),
        ),
    ]
