# Generated by Django 2.0.13 on 2020-08-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0004_auto_20200811_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_count',
            field=models.IntegerField(default=0),
        ),
    ]
