# Generated by Django 2.0.13 on 2020-08-11 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0005_ticket_ticket_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_count',
            new_name='coupon',
        ),
    ]
