# Generated by Django 2.0.13 on 2020-08-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_auto_20200811_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='expired_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='started_date',
            field=models.DateTimeField(),
        ),
    ]
