# Generated by Django 2.0.13 on 2020-08-13 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_auto_20200811_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
    ]
