# Generated by Django 2.0.13 on 2020-08-14 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0009_ticket_user'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='ticket',
        #     name='ticket_lesson',
        #     field=models.CharField(default='', max_length=128),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='ticket',
        #     name='user',
        #     field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        #     preserve_default=False,
        # ),
    ]
