# Generated by Django 2.0.13 on 2020-08-15 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0010_auto_20200814_0954'),
    ]

    operations = [
    ]
