# Generated by Django 2.0.13 on 2020-08-18 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20200817_0017'),
        ('ticket', '0014_auto_20200817_2014'),
    ]

    operations = [
    ]
