# Generated by Django 2.0.13 on 2020-09-03 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_merge_20200818_2353'),
        ('ticket', '0016_auto_20200902_1941'),
    ]

    operations = [
    ]
